# Generated by Django 4.0.3 on 2022-03-19 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(choices=[('p', 'Pedicure'), ('m', 'Manicure'), ('o', 'Onglerie'), ('s', 'Soins'), ('a', 'Achat'), ('au', 'Autres')], default='Achat', max_length=75)),
                ('date_app', models.DateField()),
                ('time_app', models.TimeField()),
            ],
            options={
                'ordering': ['date_app'],
            },
        ),
        migrations.CreateModel(
            name='gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_title', models.CharField(max_length=50)),
                ('gift_price', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['gift_title'],
            },
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=50)),
                ('type_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['type_title'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='F', max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=75)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_title', models.CharField(max_length=50)),
                ('articles_description', models.TextField(blank=True, null=True)),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.type')),
            ],
            options={
                'ordering': ['article_type'],
            },
        ),
    ]
