# Generated by Django 4.0.3 on 2022-03-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopping',
            options={'ordering': ['articles_type']},
        ),
        migrations.RenameField(
            model_name='shopping',
            old_name='article_type',
            new_name='articles_type',
        ),
        migrations.AddField(
            model_name='shopping',
            name='articles_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='shopping',
            name='image',
            field=models.ImageField(default=0, height_field=25, max_length=255, upload_to='images/', width_field=100),
            preserve_default=False,
        ),
    ]
