# Generated by Django 4.0.3 on 2022-03-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='articles_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
