# Generated by Django 4.0.3 on 2022-03-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopping_articles_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='image',
        ),
    ]
